name: merge

on:
  push:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  _3.3.5-sql:
    strategy:
      fail-fast: false
      matrix:
        branch: [3.3.5]

    runs-on: ubuntu-20.04
    steps:

    - uses: actions/checkout@v2
      with:
        ref: ${{ matrix.branch }}
        fetch-depth: 1
        repository: Rochet2/TrinityCore

    - name: Check database
      run: |
        echo "start mysql"
        sudo systemctl start mysql.service
        echo "remove user password"
        mysql -uroot -proot -e 'SET PASSWORD FOR root@localhost="";'
        echo "create databases"
        mysql -uroot -e 'create database test_mysql;'
        mysql -uroot < sql/create/create_mysql.sql
        mysql -uroot auth < sql/base/auth_database.sql
        mysql -uroot characters < sql/base/characters_database.sql
        mysql -uroot world < sql/base/dev/world_database.sql
        echo "run updates"
        chmod +x contrib/check_updates.sh
        ./contrib/check_updates.sh auth 3.3.5 auth localhost
        ./contrib/check_updates.sh characters 3.3.5 characters localhost
        ./contrib/check_updates.sh world 3.3.5 world localhost
        echo "custom/auth"; cat sql/custom/auth/*.sql | mysql -uroot auth
        echo "custom/characters"; cat sql/custom/characters/*.sql | mysql -uroot characters
        echo "custom/world"; cat sql/custom/world/*.sql | mysql -uroot world

  _master-sql:
    strategy:
      fail-fast: false
      matrix:
        branch: [master]

    runs-on: ubuntu-20.04
    steps:

    - uses: actions/checkout@v2
      with:
        ref: ${{ matrix.branch }}
        fetch-depth: 1
        repository: Rochet2/TrinityCore

    - name: Check database
      run: |
        echo "start mysql"
        sudo systemctl start mysql.service
        echo "remove user password"
        mysql -uroot -proot -e 'SET PASSWORD FOR root@localhost="";'
        echo "create databases"
        mysql -uroot -e 'create database test_mysql;'
        mysql -uroot < sql/create/create_mysql.sql
        mysql -uroot auth < sql/base/auth_database.sql
        mysql -uroot characters < sql/base/characters_database.sql
        mysql -uroot world < sql/base/dev/world_database.sql
        mysql -uroot hotfixes < sql/base/dev/hotfixes_database.sql
        echo "run updates"
        chmod +x contrib/check_updates.sh
        ./contrib/check_updates.sh auth master auth localhost
        ./contrib/check_updates.sh characters master characters localhost
        ./contrib/check_updates.sh hotfixes master hotfixes localhost
        ./contrib/check_updates.sh world master world localhost
        echo "custom/auth"; cat sql/custom/auth/*.sql | mysql -uroot auth
        echo "custom/characters"; cat sql/custom/characters/*.sql | mysql -uroot characters
        echo "custom/world"; cat sql/custom/world/*.sql | mysql -uroot world
        echo "custom/hotfixes"; cat sql/custom/hotfixes/*.sql | mysql -uroot hotfixes
