name: merge

on:
  push:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  _master:
    strategy:
      fail-fast: false
      matrix:
        branch: [master]
        pch: [ON]
    env:
      BRANCH: ${{ matrix.branch }}
      PCH: ${{ matrix.pch }}

    runs-on: ubuntu-20.04
    steps:

    - uses: actions/checkout@v2
      with:
        ref: ${{ matrix.branch }}
        fetch-depth: 1
        repository: Rochet2/TrinityCore

    - name: Dependencies
      run: |
        sudo apt-get update && sudo apt-get install -yq libboost-all-dev clang-11
    - name: Setup
      run: |
        mkdir bin
        cd bin
        cmake ../ -DWITH_WARNINGS=0 -DWITH_COREDEBUG=0 -DUSE_COREPCH=$PCH -DUSE_SCRIPTPCH=$PCH -DTOOLS=0 -DSCRIPTS=none -DSERVERS=1 -DNOJEM=0 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_FLAGS="-Werror" -DCMAKE_CXX_FLAGS="-Werror" -DCMAKE_C_FLAGS_DEBUG="-DNDEBUG" -DCMAKE_CXX_FLAGS_DEBUG="-DNDEBUG" -DCMAKE_INSTALL_PREFIX=check_install -DCMAKE_C_COMPILER=clang-11 -DCMAKE_CXX_COMPILER=clang++-11
        cd ..
    - name: Build
      run: |
        cd bin
        make -j 4 -k && make install
    - name: Find latest DB release tag
      id: find_matching_tags
      uses: Rochet2/find-matching-tags-ghapi@v1.1
      with:
        regex: ^TDB\d+\.\d+$
        sort: desc
        owner: TrinityCore
        repo: TrinityCore
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Download latest DB
      uses: i3h/download-release-asset@6a9870c8f1c561f9e67550d6177c31c2b1c49fef
      with:
        owner: TrinityCore
        repo: TrinityCore
        tag: ${{ fromJson(steps.find_matching_tags.outputs.tags)[0] }}
        file: /TDB_full.*\.7z/
        path: bin/check_install/bin
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Set configs
      run: |
        cd bin/check_install/etc
        sed "s/127.0.0.1;3306;trinity;trinity;/localhost;3306;root;;/g" worldserver.conf.dist > worldserver.conf
    - name: Build DB
      run: |
        echo "start mysql"
        sudo systemctl start mysql.service
        echo "remove user password"
        mysql -uroot -proot -e 'SET PASSWORD FOR root@localhost="";'
        echo "create databases"
        mysql -uroot -e 'create database test_mysql;'
        cd bin/check_install/bin
        7z x ./*.7z
        ./worldserver --update-databases-only

  _3-3-5:
    strategy:
      fail-fast: false
      matrix:
        branch: [3.3.5]
        pch: [ON]
    env:
      BRANCH: ${{ matrix.branch }}
      PCH: ${{ matrix.pch }}

    runs-on: ubuntu-20.04
    steps:

    - uses: actions/checkout@v2
      with:
        ref: ${{ matrix.branch }}
        fetch-depth: 1
        repository: Rochet2/TrinityCore

    - name: Dependencies
      run: |
        sudo apt-get update && sudo apt-get install -yq libboost-all-dev g++-8
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 100 --slave /usr/bin/g++ g++ /usr/bin/g++-8
    - name: Setup
      run: |
        mkdir bin
        cd bin
        cmake ../ -DWITH_WARNINGS=0 -DWITH_COREDEBUG=0 -DUSE_COREPCH=$PCH -DUSE_SCRIPTPCH=$PCH -DTOOLS=0 -DSCRIPTS=none -DSERVERS=1 -DNOJEM=0 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_FLAGS="-Werror" -DCMAKE_CXX_FLAGS="-Werror" -DCMAKE_C_FLAGS_DEBUG="-DNDEBUG" -DCMAKE_CXX_FLAGS_DEBUG="-DNDEBUG" -DCMAKE_INSTALL_PREFIX=check_install -DBUILD_TESTING=0
        cd ..
    - name: Build
      run: |
        cd bin
        make -j 4 -k && make install
    - name: Find latest DB release tag
      id: find_matching_tags
      uses: Rochet2/find-matching-tags-ghapi@v1.1
      with:
        regex: ^TDB335\.\d+$
        sort: desc
        owner: TrinityCore
        repo: TrinityCore
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Download latest DB
      uses: i3h/download-release-asset@6a9870c8f1c561f9e67550d6177c31c2b1c49fef
      with:
        owner: TrinityCore
        repo: TrinityCore
        tag: ${{ fromJson(steps.find_matching_tags.outputs.tags)[0] }}
        file: /TDB_full.*\.7z/
        path: bin/check_install/bin
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Set configs
      run: |
        cd bin/check_install/etc
        sed "s/127.0.0.1;3306;trinity;trinity;/localhost;3306;root;;/g" worldserver.conf.dist > worldserver.conf
    - name: Build DB
      run: |
        echo "start mysql"
        sudo systemctl start mysql.service
        echo "remove user password"
        mysql -uroot -proot -e 'SET PASSWORD FOR root@localhost="";'
        echo "create databases"
        mysql -uroot -e 'create database test_mysql;'
        cd bin/check_install/bin
        7z x ./*.7z
        ./worldserver --update-databases-only
